### ISSUE TITLE
请问 ele-form-group 新增加的按钮区class=“ele-form-btns” 怎么使用？

### ISSUE THREAD

**Issue by jackiehe** [dream2023/vue-ele-form#21]
请问 ele-form-group 新增加的按钮区class=“ele-form-btns” 怎么使用？
我在引用 ele-form-group的vue里定义了class, 没有效果
<style>
.ele-form-btns{
    align: "right"
}
</style>

**Comment by jackiehe** [comment]
根据网上的 写法也不行 https://www.cnblogs.com/goloving/p/9119265.html
`<style lang="css" scoped>
    .ele-form-group >>> .el-form.el-form-item.ele-form-btns{
    align: "right"
}
</style>`

**Comment by dream2023** [comment]
```css
<style>
.父级class .ele-form-btns .el-form-item__content {
  float: right;
}
</style>
```

这里注意不要加`scoped`，而是通过父class限定，提醒同时一个vue文件是可以有多个style标签的，例如：
```css
<style>
.demo .ele-form-btns .el-form-item__content {
  float: right;
}
</style>

<style scoped>
.demo {
  width: 80%;
}
</style>
```
